### ISSUE TITLE
Convert Audiee javascript object to JSON, in order to send it to the Python backend

### ISSUE THREAD

**Issue by Robinson04** [Robinson04/inoft_vocal_engine#4]

**Comment by Robinson04** [comment]
JSON.stringify cannot be used, because the Audiee object is a deep object composed of many objects

**Comment by Robinson04** [comment]
Should preferably be done in TypeScript, but you can do it in JavaScript too. I will take care of the Python backend to send the data to a database.

**Comment by Dophix** [comment]
JSON.stringify fixed so we can export important information about a project
